### PR TITLE
fixing  prevent division by zero in log message #780

### PR DESCRIPTION
**Pull request by Sbhat92**

### CODE REVIEW

**Comment by gertjanvanzwieten** [comment]
Thanks! We will merge this if you can amend the commit to address a few things:

- The lines "if not numpy.isfinite(newresnorm) or newresnorm >= resnorm: break" got repeated
- The word "newresnorm" is not meaningful for somebody that is not looking at the code, please change this message to "solution is exact"
- Please add a commit message that describes (briefly) what problem was fixed by this commit

**Comment by Sbhat92** [comment]
Reopening PR

**Comment by gertjanvanzwieten** [comment]
Thanks, looks good! Three last things:
- could you rebase your commit to master (currently it's a bit behind)
- could you remove the trailing spaces after `else:`
- could you structure a brief commit message along the guidelines of https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html (currently there is only a very long title which is formatted weirdly here on github, see https://github.com/evalf/nutils/pull/781/commits/3ff397f14cb0f61fdcb1ee870eac7bbd241a9258)

**Comment by Sbhat92** [comment]
Reopening PR with requested changes

**Review by gertjanvanzwieten — APPROVED** [review]

**Pull request merged**
